services:
  - type: web
    name: news-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free

  - type: worker
    name: news-cron-worker
    runtime: node
    buildCommand: npm install
    startCommand: npm run worker
    plan: free